apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: argo
  labels:
    app: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app-john
          image: kemir/myapp:v3
          ports:
            - containerPort: 8080