apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespce: argo
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app: my-app
